allow for node/$nodename resource form
kvaps/kubectl-node-shell pull request #36
Opened 2021-12-30 19:48 UTC by madeddie

I sometimes use this plugin with a `for node in $(kubectl get names -o node); do kubectl node-shell "$node" -- something` loop. The kubectl get names -o node outputs a list of nodenames prefixed with the `node/` type.
This change will, always, simply filter out `node/` at the beginning of the node name.

2021-12-30 21:51 UTC, kvaps requested changes
That definitely makes sense.
Please also update the plugin version on line 5

2021-12-30 21:51 UTC, kvaps commented on kubectl-node_shell
> +      node="$(echo $1 | sed 's/^node\///')"
We're trying to push hard to have no new dependencies, so let's use awk instead of sed:
```suggestion
      node="$(echo $1 | awk '{gsub(/^node\//,""); print}')"
```

2022-01-01 09:20 UTC, kvaps commented on kubectl-node_shell
> +      node="$(echo $1 | sed 's/^node\///')"
Or even better solution:
```suggestion
      node="${1#node/}"
```

2022-01-03 18:37 UTC, madeddie commented on kubectl-node_shell
> +      node="$(echo $1 | sed 's/^node\///')"
This might break some archaic `sh` versions out there, but works fine on current bash and dash, so fine by me

2022-01-06 20:06 UTC, kvaps approved these changes

2022-01-06 20:07 UTC, merged